//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.13 at 06:14:13 PM PDT 
//

package org.reactome.cancerindex.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GeneEntry")
public class GeneEntry
{

    @XmlElement(name = "id", required = true)
    protected Long id;
    @XmlElement(name = "HUGOGeneSymbol", required = true)
    protected String hugoGeneSymbol;
    @XmlElement(name = "GeneAliasCollection", required = true)
    protected List<String> geneAliasCollection;
    @XmlElement(name = "SequenceIdentificationCollection", required = true)
    protected SequenceIdentificationCollection sequenceIdentificationCollection;
    @XmlElement(name = "GeneStatusFlag", required = true)
    protected String geneStatusFlag;
    @XmlElement(name = "Sentence")
    protected List<Sentence> sentence;

    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public String getHugoGeneSymbol()
    {
        return hugoGeneSymbol;
    }

    public void setHugoGeneSymbol(String hugoGeneSymbol)
    {
        this.hugoGeneSymbol = hugoGeneSymbol;
    }

    public void setSentence(List<Sentence> sentence)
    {
        this.sentence = sentence;
    }

    public void addSentence(Sentence sentence)
    {
        if (this.sentence == null) this.sentence = new ArrayList<Sentence>();
        this.sentence.add(sentence);
    }

    /**
     * Gets the value of the geneAliasCollection property.
     * 
     * @return possible object is {@link GeneAliasCollection }
     * 
     */
    public List<String> getGeneAliasCollection()
    {
        return geneAliasCollection;
    }

    /**
     * Sets the value of the geneAliasCollection property.
     * 
     * @param value
     *            allowed object is {@link GeneAliasCollection }
     * 
     */
    public void setGeneAliasCollection(List<String> value)
    {
        this.geneAliasCollection = value;
    }

    public void addGeneAlias(String value)
    {
        if (value == null) return;
        if (geneAliasCollection == null)
            geneAliasCollection = new ArrayList<String>();
        geneAliasCollection.add(value);
    }

    /**
     * Gets the value of the sequenceIdentificationCollection property.
     * 
     * @return possible object is {@link SequenceIdentificationCollection }
     * 
     */
    public SequenceIdentificationCollection getSequenceIdentificationCollection()
    {
        return sequenceIdentificationCollection;
    }

    /**
     * Sets the value of the sequenceIdentificationCollection property.
     * 
     * @param value
     *            allowed object is {@link SequenceIdentificationCollection }
     * 
     */
    public void setSequenceIdentificationCollection(
            SequenceIdentificationCollection value)
    {
        this.sequenceIdentificationCollection = value;
    }

    /**
     * Gets the value of the geneStatusFlag property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getGeneStatusFlag()
    {
        return geneStatusFlag;
    }

    /**
     * Sets the value of the geneStatusFlag property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setGeneStatusFlag(String value)
    {
        this.geneStatusFlag = value;
    }

    /**
     * Gets the value of the sentence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the sentence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getSentence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Sentence }
     * 
     * 
     */
    public List<Sentence> getSentence()
    {
        if (sentence == null)
        {
            sentence = new ArrayList<Sentence>();
        }
        return this.sentence;
    }

}
