//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.13 at 06:14:13 PM PDT 
//


package org.reactome.CS3.cancerindex.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "GeneData")
public class GeneData {

    @XmlElement(name = "id", required = true)
    protected Long id;
    @XmlElement(name = "MatchedGeneTerm", required = true)
    protected String matchedGeneTerm;
    @XmlElement(name = "NCIGeneConceptCode", required = true)
    protected String nciGeneConceptCode;

    /**
     * Gets the value of the matchedGeneTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchedGeneTerm() {
        return matchedGeneTerm;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNciGeneConceptCode() {
        return nciGeneConceptCode;
    }

    public void setNciGeneConceptCode(String nciGeneConceptCode) {
        this.nciGeneConceptCode = nciGeneConceptCode;
    }

    /**
     * Sets the value of the matchedGeneTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchedGeneTerm(String value) {
        this.matchedGeneTerm = value;
    }

}
